In [3]:
import tensorflow as tf
import timeit
from datetime import datetime
import sys
# os and numpy
import numpy as np
import os.path


In [4]:
repo_base = "/net/jabba/home0/am611608/source/SAMPO/cas_test/nn/mutation_toy_case_best"

model_name = "saved_model.pb"
model_url = os.path.join(repo_base, model_name)

kmodel = tf.keras.models.load_model(repo_base, compile=False)
model  = tf.saved_model.load(repo_base)



In [14]:
kmodel.variables

[<tf.Variable 'dense_32/kernel:0' shape=(2, 20) dtype=float32, numpy=
 array([[ 5.98769672e-02, -1.34349918e+00, -4.94246669e-02,
          1.03842214e-01, -1.47437558e-01,  3.73599072e-08,
         -2.12743461e-01, -2.21216679e+00, -1.15546513e+00,
         -7.47017980e-01,  5.81722558e-02, -1.50226638e-01,
         -4.99471501e-02, -1.96554065e-02,  2.44456694e-01,
         -1.62592590e-01,  2.94422626e-01, -1.39803410e-01,
         -8.13128948e-02, -2.69860625e-01],
        [ 1.02312458e+00, -1.48315094e-02,  1.89534032e+00,
          1.48748469e+00,  2.69546814e-04,  1.11365274e-07,
          1.36719990e+00,  9.30041969e-02, -2.47465670e-01,
         -1.06920181e-02,  1.50789297e+00, -1.04117417e+00,
         -3.67300399e-03, -1.83433604e+00, -2.46083951e+00,
         -2.10983109e+00, -1.42802858e+00, -3.76966596e+00,
          2.08692136e-03,  5.90986431e-01]], dtype=float32)>,
 <tf.Variable 'dense_32/bias:0' shape=(20,) dtype=float32, numpy=
 array([-4.2685175e-01,  7.2431065e-02

In [15]:
kmodel.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 1, 2)]            0         
_________________________________________________________________
dense (Dense)                (None, 1, 20)             60        
_________________________________________________________________
batch_normalization (BatchNo (None, 1, 20)             80        
_________________________________________________________________
dense_1 (Dense)              (None, 1, 20)             420       
_________________________________________________________________
batch_normalization_1 (Batch (None, 1, 20)             80        
_________________________________________________________________
dense_2 (Dense)              (None, 1, 20)             420       
_________________________________________________________________
batch_normalization_2 (Batch (None, 1, 20)             80    

In [18]:
textX=tf.random.uniform((5,1,2))
kmodel.predict(textX)

array([[[ 1.0000682e+00,  1.0000641e+00, -7.2076917e-05,  9.8461413e-01,
          9.4845319e-01,  8.4310639e-01,  8.5804725e-01,  9.8603719e-01]],

       [[ 1.4956534e-01,  1.4956254e-01,  8.5043061e-01,  5.9987116e-01,
          5.4811186e-01,  3.4893477e-01,  3.6485258e-01,  5.8411789e-01]],

       [[ 9.9993438e-01,  9.9995565e-01,  1.5692413e-04,  9.7325790e-01,
          9.4115555e-01,  7.2741568e-01,  7.5193453e-01,  9.7684419e-01]],

       [[ 9.9983388e-01,  9.9984723e-01,  2.1892786e-04,  9.6285367e-01,
          8.1514525e-01,  6.2047046e-01,  6.5254456e-01,  9.6925426e-01]],

       [[ 9.9783349e-01,  9.9786389e-01,  2.2924542e-03,  8.3314186e-01,
          8.7435812e-01,  1.4036739e-01,  1.5519460e-01,  8.8723910e-01]]],
      dtype=float32)

In [26]:
l=kmodel.get_layer("input_1")

In [29]:
l.build((1,1,2))

In [34]:
k=kmodel.build(input_shape=(1,1,2))

In [35]:
k.summary()

AttributeError: 'NoneType' object has no attribute 'summary'

In [ ]:

# python import_pb_to_tensorboard.py --model_dir /net/jabba/home0/am611608/source/simple-hpc/models/sampo-model/cas_test/nn/mutation_toy_case_best --log_dir /tmp/tensorflow_logdir
!tensorboard --logdir=/tmp/tensorflow_logdir