In [1]:
import tensorflow as tf

def load_pb(path_to_pb):
    with tf.compat.v1.gfile.GFile(path_to_pb, "rb") as f:
        graph_def = tf.compat.v1.GraphDef()
        graph_def.ParseFromString(f.read())
    with tf.Graph().as_default() as graph:
        tf.import_graph_def(graph_def, name='')
        return graph

In [30]:
model_path ="/home/cea/am611608/source/simple-hpc/models/sampo-model/cas_test/nn/mutation_toy_case_best"
model = tf.saved_model.load(model_path)
# import os
# model = load_pb(os.path.join(model_path, "saved_model.pb")) #this won't work because "freezing" issues ??

# Running NN feed forward
The input shape is `[?, 1, 2]` with `?` being the batch size.

With `.pb` files, we can dynamically adapt the batch size using tensorflow.

In [31]:
x = tf.random.uniform(shape=[1000000, 1, 2]) #this works
x = tf.random.uniform(shape=[1, 1, 2]) #this works
x = tf.random.uniform(shape=[1, 4, 2]) #this won't work because the input vec size is not [4, 2]
x = tf.random.uniform(shape=[5, 1, 2]) #this works
x

<tf.Tensor: shape=(5, 1, 2), dtype=float32, numpy=
array([[[0.1427691 , 0.9707074 ]],

       [[0.69610715, 0.37932312]],

       [[0.01770687, 0.9211359 ]],

       [[0.14073145, 0.9008664 ]],

       [[0.9727715 , 0.59700894]]], dtype=float32)>

When running the feed forward pass, we will get `batch size` time our result.

In [32]:
model(x)

<tf.Tensor: shape=(5, 1, 8), dtype=float32, numpy=
array([[[ 1.0000470e+00,  1.0000081e+00, -1.6696751e-04,  9.9733740e-01,
          8.0210936e-01,  9.7454423e-01,  9.7762620e-01,  9.9733686e-01]],

       [[ 9.9870133e-01,  9.9872971e-01,  1.4185756e-03,  8.5547161e-01,
          8.7769473e-01,  1.4302637e-01,  1.5868655e-01,  9.0967846e-01]],

       [[ 9.9995786e-01,  1.0000159e+00,  3.1614304e-04,  9.9336976e-01,
          6.5172750e-01,  9.3038839e-01,  9.3756831e-01,  9.9403298e-01]],

       [[ 9.9993342e-01,  9.9994391e-01,  1.4112890e-04,  9.9131149e-01,
          7.9718298e-01,  9.1209805e-01,  9.2062402e-01,  9.9214983e-01]],

       [[ 9.9979830e-01,  9.9979931e-01,  2.0188093e-04,  9.5462328e-01,
          9.7193795e-01,  5.4109371e-01,  5.7728046e-01,  9.6435177e-01]]],
      dtype=float32)>

# Trying to visualize the execution graph

In [26]:
from datetime import datetime
from packaging import version

import tensorflow as tf
from tensorflow import keras

print("TensorFlow version: ", tf.__version__)
assert version.parse(tf.__version__).release[0] >= 2, \
    "This notebook requires TensorFlow 2.0 or above."

import tensorboard
tensorboard.__version__

# Clear any logs from previous runs
!rm -rf ./logs/


TensorFlow version:  2.6.2


In [42]:
kmodel = tf.keras.models.load_model(model_path)
# kmodel.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])


OSError: SavedModel file does not exist at: /home/cea/am611608/source/simple-hpc/models/sampo-model/cas_test/nn/mutation_toy_case_best/saved_model.pb/{saved_model.pbtxt|saved_model.pb}

In [41]:
kmodel.evaluate(x)

AttributeError: in user code:

    /net/jabba/home0/am611608/source/simple-hpc/venv/lib64/python3.6/site-packages/tensorflow/python/keras/engine/training.py:941 test_function  *
        outputs = self.distribute_strategy.run(
    /net/jabba/home0/am611608/source/simple-hpc/venv/lib64/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py:951 run  **
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /net/jabba/home0/am611608/source/simple-hpc/venv/lib64/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py:2290 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /net/jabba/home0/am611608/source/simple-hpc/venv/lib64/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py:2649 _call_for_each_replica
        return fn(*args, **kwargs)
    /net/jabba/home0/am611608/source/simple-hpc/venv/lib64/python3.6/site-packages/tensorflow/python/keras/engine/training.py:914 test_step  **
        self.compiled_metrics.update_state(y, y_pred, sample_weight)
    /net/jabba/home0/am611608/source/simple-hpc/venv/lib64/python3.6/site-packages/tensorflow/python/keras/engine/compile_utils.py:391 update_state
        self._build(y_pred, y_true)
    /net/jabba/home0/am611608/source/simple-hpc/venv/lib64/python3.6/site-packages/tensorflow/python/keras/engine/compile_utils.py:322 _build
        self._metrics, y_true, y_pred)
    /net/jabba/home0/am611608/source/simple-hpc/venv/lib64/python3.6/site-packages/tensorflow/python/util/nest.py:1118 map_structure_up_to
        **kwargs)
    /net/jabba/home0/am611608/source/simple-hpc/venv/lib64/python3.6/site-packages/tensorflow/python/util/nest.py:1214 map_structure_with_tuple_paths_up_to
        *flat_value_lists)]
    /net/jabba/home0/am611608/source/simple-hpc/venv/lib64/python3.6/site-packages/tensorflow/python/util/nest.py:1213 <listcomp>
        results = [func(*args, **kwargs) for args in zip(flat_path_list,
    /net/jabba/home0/am611608/source/simple-hpc/venv/lib64/python3.6/site-packages/tensorflow/python/util/nest.py:1116 <lambda>
        lambda _, *values: func(*values),  # Discards the path arg.
    /net/jabba/home0/am611608/source/simple-hpc/venv/lib64/python3.6/site-packages/tensorflow/python/keras/engine/compile_utils.py:421 _get_metric_objects
        return [self._get_metric_object(m, y_t, y_p) for m in metrics]
    /net/jabba/home0/am611608/source/simple-hpc/venv/lib64/python3.6/site-packages/tensorflow/python/keras/engine/compile_utils.py:421 <listcomp>
        return [self._get_metric_object(m, y_t, y_p) for m in metrics]
    /net/jabba/home0/am611608/source/simple-hpc/venv/lib64/python3.6/site-packages/tensorflow/python/keras/engine/compile_utils.py:442 _get_metric_object
        y_t_rank = len(y_t.shape.as_list())

    AttributeError: 'NoneType' object has no attribute 'shape'


In [37]:
a = kmodel.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
