In [1]:
import tensorflow as tf

def load_pb(path_to_pb):
    with tf.compat.v1.gfile.GFile(path_to_pb, "rb") as f:
        graph_def = tf.compat.v1.GraphDef()
        graph_def.ParseFromString(f.read())
    with tf.Graph().as_default() as graph:
        tf.import_graph_def(graph_def, name='')
        return graph

In [3]:
model_path ="/home/cea/am611608/source/simple-hpc/models/sampo-model/cas_test/nn/mutation_toy_case_best/savec_model.pb"
model = tf.saved_model.load(model_path)
# import os
# model = load_pb(os.path.join(model_path, "saved_model.pb")) #this won't work because "freezing" issues ??

In [10]:
import tensorflow.keras as keras
model = keras.models.load_model(model_path, compile=False)

# Running NN feed forward
The input shape is `[?, 1, 2]` with `?` being the batch size.

With `.pb` files, we can dynamically adapt the batch size using tensorflow.

In [11]:
x = tf.random.uniform(shape=[1000000, 1, 2]) #this works
x = tf.random.uniform(shape=[1, 1, 2]) #this works
x = tf.random.uniform(shape=[1, 4, 2]) #this won't work because the input vec size is not [4, 2]
x = tf.random.uniform(shape=[5, 1, 2]) #this works
x

<tf.Tensor: shape=(5, 1, 2), dtype=float32, numpy=
array([[[0.851226  , 0.24256265]],

       [[0.308357  , 0.67497647]],

       [[0.37940705, 0.24955785]],

       [[0.7900673 , 0.35857797]],

       [[0.35490656, 0.59782434]]], dtype=float32)>

When running the feed forward pass, we will get `batch size` time our result.

In [12]:
model(x)

<tf.Tensor: shape=(5, 1, 8), dtype=float32, numpy=
array([[[9.3397111e-01, 9.3398947e-01, 6.6095054e-02, 7.1410370e-01,
         8.1382418e-01, 2.0788598e-01, 2.1809448e-01, 7.5530356e-01]],

       [[9.9986613e-01, 9.9986404e-01, 1.2493134e-04, 9.6699774e-01,
         8.5918379e-01, 6.6183472e-01, 6.9125378e-01, 9.7201562e-01]],

       [[9.7296405e-01, 9.7298741e-01, 2.7127773e-02, 7.1851879e-01,
         7.3312771e-01, 1.6771740e-01, 1.7986509e-01, 7.6515841e-01]],

       [[9.9792218e-01, 9.9795532e-01, 2.2155643e-03, 8.3640909e-01,
         8.7968493e-01, 1.4069468e-01, 1.5559848e-01, 8.9056581e-01]],

       [[9.9986303e-01, 9.9986476e-01, 1.3926625e-04, 9.5487618e-01,
         8.6670578e-01, 5.4265457e-01, 5.7891345e-01, 9.6442497e-01]]],
      dtype=float32)>

# Trying to visualize the execution graph

In [13]:
import tensorflow as tf
from tensorflow.python.platform import gfile
# import 
# tf.compat.v1.keras.models.load_model(model_path, compile=False)

with tf.compat.v1.Session() as sess:
    model_filename =os.path.join(model_path,'saved_model.pb')
    with gfile.FastGFile(model_filename, 'rb') as f:
        graph_def = tf.compat.v1.GraphDef()
        graph_def.ParseFromString(f.read())
        g_in = tf.compat.v1.import_graph_def(graph_def)
# LOGDIR='/net/jabba/home0/am611608/source/simple-hpc/models/logs'
# train_writer = tf.compat.v1.summary.FileWriter(LOGDIR)
# train_writer.add_graph(sess.graph)

Instructions for updating:
Use tf.gfile.GFile.


DecodeError: Error parsing message with type 'tensorflow.GraphDef'

In [26]:
from datetime import datetime
from packaging import version

import tensorflow as tf
from tensorflow import keras

print("TensorFlow version: ", tf.__version__)
assert version.parse(tf.__version__).release[0] >= 2, \
    "This notebook requires TensorFlow 2.0 or above."

import tensorboard
tensorboard.__version__

# Clear any logs from previous runs
!rm -rf ./logs/


TensorFlow version:  2.6.2


In [17]:
kmodel = tf.keras.models.load_model(model_path, compile=False)
# kmodel.build((1,1,2))
# kmodel.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [21]:
kmodel.call(x)

<tf.Tensor: shape=(5, 1, 8), dtype=float32, numpy=
array([[[9.3397111e-01, 9.3398947e-01, 6.6095054e-02, 7.1410370e-01,
         8.1382418e-01, 2.0788598e-01, 2.1809448e-01, 7.5530356e-01]],

       [[9.9986613e-01, 9.9986404e-01, 1.2493134e-04, 9.6699774e-01,
         8.5918379e-01, 6.6183472e-01, 6.9125378e-01, 9.7201562e-01]],

       [[9.7296405e-01, 9.7298741e-01, 2.7127773e-02, 7.1851879e-01,
         7.3312771e-01, 1.6771740e-01, 1.7986509e-01, 7.6515841e-01]],

       [[9.9792218e-01, 9.9795532e-01, 2.2155643e-03, 8.3640909e-01,
         8.7968493e-01, 1.4069468e-01, 1.5559848e-01, 8.9056581e-01]],

       [[9.9986303e-01, 9.9986476e-01, 1.3926625e-04, 9.5487618e-01,
         8.6670578e-01, 5.4265457e-01, 5.7891345e-01, 9.6442497e-01]]],
      dtype=float32)>

In [51]:
kmodel.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
